const clothes = [
    {
        id: 1,
        image: "./images/Mens/cargo-1.png",
        title: "cargo-pant-1",
        price: 1200,
        category: "cargo-pant",
        description: "Stylish and comfortable cargo pant perfect for casual outing in olive green color",
        color: "olive-green",
        rating: 4.1,
    },
    {
        id: 2,
        image: "./images/Mens/cargo-2.jpg",
        title: "cargo-pant-2",
        price: 1200,
        category: "cargo-pant",
        description: "Stylish and comfortable cargo pant perfect for casual outing in navy blue color.",
        color: "navy-blue",
        rating: 4.2,
    },
    {
        id: 3,
        image: "./images/Mens/cargo-3.jpg",
        title: "cargo-pant-3",
        price: 1200,
        category: "cargo-pant",
        description: "Stylish and comfortable cargo pant perfect for casual outing in dark grey color.",
        color: "dark-grey",
        rating: 4.3,
    },
    {
        id: 4,
        image: "./images/Mens/cargo-4.jpg",
        title: "cargo-pant-4",
        price: 1200,
        category: "cargo-pant",
        description: "Stylish and comfortable cargo pant perfect for casual outing in red color.",
        color: "red",
        rating: 4.2,
    },
    {
        id: 5,
        image: "./images/Mens/cargo-5.jpg",
        title: "cargo-pant-5",
        price: 1200,
        category: "cargo-pant",
        description: "Stylish and comfortable cargo pant perfect for casual outing in black color.",
        color: "black",
        rating: 4.6,
    },
    {
        id: 6,
        image: "./images/Mens/hoddie-1.jpeg",
        title: "hoddie-1",
        price: 1000,
        category: "hoddie",
        description: "Stylish and comfortable hoddie perfect for casual outing in black color.",
        color: "black",
        rating: 4.8,
    },
    {
        id: 7,
        image: "./images/Mens/hoddie-2.jpeg",
        title: "hoddie-2",
        price: 1000,
        category: "hoddie",
        description: "Stylish and comfortable hoddie perfect for casual outing in purple color.",
        color: "purple",
        rating: 4.0,
    },
    {
        id: 8,
        image: "./images/Mens/hoddie-3.jpeg",
        title: "hoddie-3",
        price: 1000,
        category: "hoddie",
        description: "Stylish and comfortable hoddie perfect for casual outing in beige color.",
        color: "beige",
        rating: 4.7,
    },
    {
        id: 9,
        image: "./images/Mens/hoddie-4.jpeg",
        title: "hoddie-4",
        price: 1000,
        category: "hoddie",
        description: "Stylish and comfortable hoddie perfect for casual outing in blue color.",
        color: "blue",
        rating: 4.6,
    },
    {
        id: 10,
        image: "./images/Mens/hoddie-5.png",
        title: "hoddie-5",
        price: 1000,
        category: "hoddie",
        description: "Stylish and comfortable hoddie perfect for casual outing in grey color.",
        color: "grey",
        rating: 4.5,
    },
    {
        id: 11,
        image: "./images/Mens/jacket-1.png",
        title: "jacket-1",
        price: 3200,
        category: "jacket",
        description: "Stylish and comfortable jacket perfect for casual outing in navy blue color.",
        color: "navy-blue",
        rating: 4.5,
    },
    {
        id: 12,
        image: "./images/Mens/jacket-2.png",
        title: "jacket-2",
        price: 3200,
        category: "jacket",
        description: "Stylish and comfortable jacket perfect for casual outing in black color.",
        color: "black",
        rating: 4.8,
    },
    {
        id: 13,
        image: "./images/Mens/jacket-3.jpg",
        title: "jacket-3",
        price: 3200,
        category: "jacket",
        description: "Stylish and comfortable jacket perfect for casual outing in grey color.",
        color: "grey",
        rating: 4.5,
    },
    {
        id: 14,
        image: "./images/Mens/jacket-4.jpg",
        title: "jacket-4",
        price: 3200,
        category: "jacket",
        description: "Stylish and comfortable jacket perfect for casual outing in brown color.",
        color: "brown",
        rating: 4.6,
    },
    {
        id: 15,
        image: "./images/Mens/jacket-5.jpg",
        title: "jacket-5",
        price: 3200,
        category: "jacket",
        description: "Stylish and comfortable jacket perfect for casual outing in maroon color.",
        color: "maroon",
        rating: 4.0,
    },
    {
        id: 16,
        image: "./images/Mens/jeans-1.png",
        title: "jeans-1",
        price: 1500,
        category: "jeans",
        description: "Stylish and comfortable jeans perfect for casual outing in beige color.",
        color: "beige",
        rating: 4.5,
    },
    {
        id: 17,
        image: "./images/Mens/jeans-2.png",
        title: "jeans-2",
        price: 1500,
        category: "jeans",
        description: "Stylish and comfortable jeans perfect for casual outing in dark grey color.",
        color: "dark-grey",
        rating: 4.4,
    },
    {
        id: 18,
        image: "./images/Mens/jeans-3.png",
        title: "jeans-3",
        price: 1500,
        category: "jeans",
        description: "Stylish and comfortable jeans perfect for casual outing in brown color.",
        color: "brown",
        rating: 4.3,
    },
    {
        id: 19,
        image: "./images/Mens/jeans-4.png",
        title: "jeans-4",
        price: 1500,
        category: "jeans",
        description: "Stylish and comfortable jeans perfect for casual outing in light grey color.",
        color: "light-grey",
        rating: 4.6,
    },
    {
        id: 20,
        image: "./images/Mens/jeans-5.png",
        title: "jeans-5",
        price: 1500,
        category: "jeans",
        description: "Stylish and comfortable jeans perfect for casual outing in sky blue color.",
        color: "sky-blue",
        rating: 4.7,
    },
    {
        id: 21,
        image: "./images/Mens/shirt-1.jpg",
        title: "shirt-1",
        price: 1300,
        category: "shirt",
        description: "Stylish and comfortable shirt perfect for casual outing in red color.",
        color: "red",
        rating: 4.0,
    },
    {
        id: 22,
        image: "./images/Mens/shirt-2.jpg",
        title: "shirt-2",
        price: 1300,
        category: "shirt",
        description: "Stylish and comfortable shirt perfect for casual outing in green color.",
        color: "green",
        rating: 3.7,
    },
    {
        id: 23,
        image: "./images/Mens/shirt-3.jpg",
        title: "shirt-3",
        price: 1300,
        category: "shirt",
        description: "Stylish and comfortable shirt perfect for casual outing in black color.",
        color: "black",
        rating: 4.9,
    },
    {
        id: 24,
        image: "./images/Mens/shirt-4.jpg",
        title: "shirt-4",
        price: 1300,
        category: "shirt",
        description: "Stylish and comfortable shirt perfect for casual outing in light blue color.",
        color: "light-blue",
        rating: 4.4,
    },
    {
        id: 25,
        image: "./images/Mens/shirt-5.jpg",
        title: "shirt-1",
        price: 1300,
        category: "shirt",
        description: "Stylish and comfortable shirt perfect for casual outing in grey color.",
        color: "grey",
        rating: 4.0,
    },
    {
        id: 26,
        image: "./images/Mens/trouser-1.png",
        title: "trouser-1",
        price: 1800,
        category: "trouser",
        description: "Stylish and comfortable trouser perfect for casual outing in black color.",
        color: "black",
        rating: 4.8,
    },
    {
        id: 27,
        image: "./images/Mens/trouser-2.png",
        title: "trouser-2",
        price: 1800,
        category: "trouser",
        description: "Stylish and comfortable trouser perfect for casual outing in grey color.",
        color: "grey",
        rating: 4.6,
    },
    {
        id: 28,
        image: "./images/Mens/trouser-3.png",
        title: "trouser-3",
        price: 1800,
        category: "trouser",
        description: "Stylish and comfortable trouser perfect for casual outing in blue color.",
        color: "blue",
        rating: 4.8,
    },
    {
        id: 29,
        image: "./images/Mens/trouser-4.jpg",
        title: "trouser-4",
        price: 1800,
        category: "trouser",
        description: "Stylish and comfortable trouser perfect for casual outing in red color.",
        color: "red",
        rating: 4.2,
    },
    {
        id: 30,
        image: "./images/Mens/trouser-5.jpg",
        title: "trouser-5",
        price: 1800,
        category: "trouser",
        description: "Stylish and comfortable trouser perfect for casual outing in green color.",
        color: "green",
        rating: 4.0,
    },
]


const SUPABASE_URL = "https://ymhqxlsdwqhymyxczabk.supabase.co";
const SUPABASE_ANON_KEY ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InltaHF4bHNkd3FoeW15eGN6YWJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NjY0NzMsImV4cCI6MjA3MTU0MjQ3M30.3_3rKa1Asgx2DT48cL032404z4WPUlk9APDfIBaQOpY";

const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

const inputEmail = document.getElementById("email");
const inputPassword = document.getElementById("password");
const continueBtn = document.getElementById("continue");